import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { name, email, phone, company, topic, message } = body;

    console.log("=== DISPATCHING CONTACT FORM EMAIL TO priya@callwithlisa.in ===");
    console.log(`From: ${name} <${email}> | Phone: ${phone || "N/A"}`);
    console.log(`Company: ${company || "N/A"} | Topic: ${topic}`);

    // Create SMTP Transporter using Gmail credentials
    const transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 587,
      secure: false, // TLS
      auth: {
        user: "upadhyaypriya974@gmail.com",
        pass: "ygzbyktvqmbnkkaa",
      },
    });

    const mailOptions = {
      from: `"Lisa AI Contact Form" <upadhyaypriya974@gmail.com>`,
      to: "priya@callwithlisa.in",
      cc: "upadhyaypriya974@gmail.com",
      replyTo: email || undefined,
      subject: `[Lisa AI Lead Inquiry] ${topic || "General Inquiry"} - ${name || "Website Lead"}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #E2E8F0; padding: 24px; border-radius: 12px; background-color: #FFFFFF;">
          <h2 style="color: #0F172A; margin-top: 0; border-bottom: 2px solid #C4F135; padding-bottom: 8px;">New Lisa AI Contact Inquiry</h2>
          <p style="font-size: 15px; color: #334155;">You have received a new contact submission from your website <strong>callwithlisa.in</strong>.</p>
          
          <table style="width: 100%; border-collapse: collapse; margin-top: 16px;">
            <tr>
              <td style="padding: 8px; font-weight: bold; color: #475569; width: 140px;">Name:</td>
              <td style="padding: 8px; color: #0F172A;">${name || "N/A"}</td>
            </tr>
            <tr>
              <td style="padding: 8px; font-weight: bold; color: #475569;">Email:</td>
              <td style="padding: 8px; color: #0F172A;"><a href="mailto:${email}">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px; font-weight: bold; color: #475569;">Phone:</td>
              <td style="padding: 8px; color: #0F172A;"><a href="tel:${phone}">${phone || "N/A"}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px; font-weight: bold; color: #475569;">Company:</td>
              <td style="padding: 8px; color: #0F172A;">${company || "N/A"}</td>
            </tr>
            <tr>
              <td style="padding: 8px; font-weight: bold; color: #475569;">Inquiry Topic:</td>
              <td style="padding: 8px; color: #0F172A;"><strong>${topic || "General Inquiry"}</strong></td>
            </tr>
          </table>

          <div style="margin-top: 20px; background-color: #F8FAFC; padding: 16px; border-radius: 8px; border-left: 4px solid #0F172A;">
            <p style="margin: 0; font-weight: bold; color: #475569; font-size: 13px;">MESSAGE CONTENT:</p>
            <p style="margin-top: 8px; color: #0F172A; white-space: pre-wrap; font-size: 14px;">${message || "No additional message provided."}</p>
          </div>

          <p style="margin-top: 24px; font-size: 12px; color: #94A3B8; text-align: center;">This message was automatically generated by Lisa AI web server.</p>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log("Email sent successfully:", info.messageId);

    return NextResponse.json({
      success: true,
      messageId: info.messageId,
      recipient: "priya@callwithlisa.in",
      message: "Your message has been successfully sent to Priya Upadhyay (priya@callwithlisa.in).",
    });
  } catch (err: any) {
    console.error("Error sending contact email:", err);
    return NextResponse.json(
      { success: false, error: err?.message || "Failed to process email dispatch." },
      { status: 500 }
    );
  }
}
